failure-threshold: style
ignored:
  # https://github.com/hadolint/hadolint/issues/422
  - DL3003
  # repository pinning is better than package pinning for apk
  # https://stschindler.medium.com/the-problem-with-docker-and-alpines-package-pinning-18346593e891
  - DL3018
  # shellcheck doesn't recognize the SHELL sh -eux command
  - SC2164
