version: '3.8'

services:
  hadolint:
    image: hadolint/hadolint:v2.14.0@sha256:27086352fd5e1907ea2b934eb1023f217c5ae087992eb59fde121dce9c9ff21e
    working_dir: /mnt
    volumes:
      - ./:/mnt
    entrypoint: hadolint
    tty: true

  shellcheck:
    image: koalaman/shellcheck:v0.11.0@sha256:61862eba1fcf09a484ebcc6feea46f1782532571a34ed51fedf90dd25f925a8d
    volumes:
      - ./:/mnt

  bats:
    build:
      context: .
      target: test
    volumes:
      - ./:/usr/src
    entrypoint: bats

  pgrst_dev:
    build: .
    volumes:
      - ./:/usr/src

