version: '3.8'

services:
  hadolint:
    image: hadolint/hadolint:v2.12.0@sha256:30a8fd2e785ab6176eed53f74769e04f125afb2f74a6c52aef7d463583b6d45e
    working_dir: /mnt
    volumes:
      - ./:/mnt
    entrypoint: hadolint
    tty: true

  shellcheck:
    image: koalaman/shellcheck:v0.11.0@sha256:61862eba1fcf09a484ebcc6feea46f1782532571a34ed51fedf90dd25f925a8d
    volumes:
      - ./:/mnt

  bats:
    build:
      context: .
      target: test
    volumes:
      - ./:/usr/src
    entrypoint: bats

  pgrst_dev:
    build: .
    volumes:
      - ./:/usr/src

