version: '3.8'

services:
  hadolint:
    image: hadolint/hadolint:v2.10.0@sha256:93f0afd12c3be5d732227c0226dd8e7bb84f79319a773d7f8519e55f958ba415
    working_dir: /mnt
    volumes:
      - ./:/mnt
    entrypoint: hadolint
    tty: true

  shellcheck:
    image: koalaman/shellcheck:v0.8.0@sha256:4c4427336d2b4bdb054a1e97396fa2e9ca0c329a1f43f831b99bcaae4ac24fcd
    volumes:
      - ./:/mnt

  bats:
    build:
      context: .
      target: test
    volumes:
      - ./:/usr/src
    entrypoint: bats

  pgrst_dev:
    build: .
    volumes:
      - ./:/usr/src

