version: '3.8'

services:
  hadolint:
    image: hadolint/hadolint:v2.13.1@sha256:1fd499f411a9ff121fda3207af1c8d32e2a92648c19fb1847553c5b79ca4c281
    working_dir: /mnt
    volumes:
      - ./:/mnt
    entrypoint: hadolint
    tty: true

  shellcheck:
    image: koalaman/shellcheck:v0.11.0@sha256:61862eba1fcf09a484ebcc6feea46f1782532571a34ed51fedf90dd25f925a8d
    volumes:
      - ./:/mnt

  bats:
    build:
      context: .
      target: test
    volumes:
      - ./:/usr/src
    entrypoint: bats

  pgrst_dev:
    build: .
    volumes:
      - ./:/usr/src

