version: '3.8'

services:
  hadolint:
    image: hadolint/hadolint:v2.9.2@sha256:6c9e9654461b7cf81e1797d4ece13942207e0a92d1a33c8e0275260d39d61e6a
    working_dir: /mnt
    volumes:
      - ./:/mnt
    entrypoint: hadolint
    tty: true

  shellcheck:
    image: koalaman/shellcheck:v0.8.0@sha256:4c4427336d2b4bdb054a1e97396fa2e9ca0c329a1f43f831b99bcaae4ac24fcd
    volumes:
      - ./:/mnt

  bats:
    build:
      context: .
      target: test
    volumes:
      - ./:/usr/src
    entrypoint: bats

  pgrst_dev:
    build: .
    volumes:
      - ./:/usr/src

