#!/usr/bin/env bash
#
# USAGE:
# with_pgrst <command>
# The command is executed with PostgREST available on localhost:3000.
# Expects all PostgREST configuration to be provided in-database.
# PostgREST is shutdown when the script exits.
#
set -Eeuo pipefail

export PGRST_DB_POOL=1

"$(dirname "$0")/run_pgrst" &
pid=$!

trap 'kill $pid 2> /dev/null' EXIT

# wait for pgrst to be up and ready
timeout 2s bash <<'EOF'
  if [ -v PGRST_SERVER_UNIX_SOCKET ]; then
    until (curl --silent --head -o /dev/null --fail --unix-socket "$PGRST_SERVER_UNIX_SOCKET" http://localhost); do
      sleep 1
    done
  else
    until (curl --silent --head -o /dev/null --fail http://localhost:${PGRST_SERVER_PORT:-3000}); do
      sleep 1
    done
  fi
EOF

("$@")
