#!/usr/bin/env bash
#
# USAGE:
# with_pgrst <command>
# The command is executed with PostgREST available on localhost:3000.
# Expects all PostgREST configuration to be provided in-database.
# PostgREST is shutdown when the script exits.
#
set -Eeuo pipefail

export PGRST_DB_POOL=1

"$(dirname "$0")/run_pgrst" &
pid=$!

trap 'kill $pid 2> /dev/null' EXIT

# wait for pgrst to be up and ready
# uses admin /ready endpoint, but falls back to regular connection for PostgREST v9
timeout 2s bash <<EOF
  until (curl --silent -o /dev/null --fail http://localhost:3001/ready || curl --silent -o /dev/null --fail http://localhost:3000); do
    sleep 1
  done
EOF

("$@")
