#!/usr/bin/env bash
#
# Helper to run PostgREST with libpq environment variables
#
set -Eeuo pipefail

PGUSER="${PGRST_DEV_AUTHENTICATOR:-$PGUSER}"
# v10 and up have an admin endpoint available for health checks
PGRST_ADMIN_SERVER_PORT="${PGRST_ADMIN_SERVER_PORT:-3001}"
export PGUSER PGRST_ADMIN_SERVER_PORT

exec postgrest "$@"
