#!/usr/bin/env bash
#
# USAGE:
# with_pgrst <command>
# The command is executed with PostgREST available on localhost:3000.
# Expects all PostgREST configuration to be provided in-database.
# PostgREST is shutdown when the script exits.
#
set -Eeuo pipefail

# helper from pg_dev base image
# shellcheck disable=SC1090
source "$(command -v _with_tmp_dir)"

export PGRST_DB_POOL=1

logfile="$PG_DEV_TMP_DIR/with_pgrst.log"

_with_menu_item r "show output for PostgREST" cat "$logfile"

run_pgrst > "$logfile" 2>&1 &
pid=$!

echo "kill $pid 2> /dev/null" >> "$PG_DEV_TMP_DIR/cleanup"

# wait for pgrst to be up and ready
timeout 5s bash <<EOF
  until curl --silent -o /dev/null --fail http://localhost:3000; do
    sleep 1
  done
EOF

("$@")
