#!/usr/bin/env bash
#
# USAGE:
# with_pgrst <command>
# The command is executed with PostgREST available on localhost:3000.
# Expects all PostgREST configuration to be provided in-database.
# PostgREST is shutdown when the script exits.
#
set -Eeuo pipefail

export PGRST_DB_POOL=1

run_pgrst > /dev/null 2>&1 &
pid=$!

function cleanup() {
  kill $pid 2> /dev/null
}
trap cleanup EXIT

# wait for pgrst to be up and ready
timeout 5s bash <<EOF
  until curl --silent -o /dev/null --fail http://localhost:3000; do
    sleep 1
  done
EOF

# Allow re-splitting of arguments on purpose
# shellcheck disable=SC2068
($@)
