name: Pull Request

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Hadolint
        run: docker compose run --rm hadolint Dockerfile
      - name: Shellcheck
        run: docker compose run --rm shellcheck tools/*

  build-test:
    strategy:
      matrix:
        pg: [10, 11, 12, 13, 14, 14-invoker]
        pgrst: [8, 9, 10-pre]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Build
        uses: docker/build-push-action@v3.1.0
        with:
          build-args: |
            PG_MAJOR=${{ matrix.pg }}
            PGRST_MAJOR=${{ matrix.pgrst }}
      - name: Build Test
        uses: docker/build-push-action@v3.1.0
        with:
          build-args: |
            PG_MAJOR=${{ matrix.pg }}
            PGRST_MAJOR=${{ matrix.pgrst }}
          target: test
      - name: Test
        run: DOCKER_BUILDKIT=1 docker compose run --rm bats test
