name: Push to main

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Hadolint
        run: docker compose run --rm hadolint Dockerfile
      - name: Shellcheck
        run: docker compose run --rm shellcheck tools/*

  build-test-push:
    needs: lint
    strategy:
      matrix:
        pg: [12, 13, 14, 14-invoker, 15, 16]
        pgrst: [10, 11, 12, devel]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Login to Docker
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v6.18.0
        with:
          build-args: |
            PG_MAJOR=${{ matrix.pg }}
            PGRST_MAJOR=${{ matrix.pgrst }}
      - name: Build Test
        uses: docker/build-push-action@v6.18.0
        with:
          build-args: |
            PG_MAJOR=${{ matrix.pg }}
            PGRST_MAJOR=${{ matrix.pgrst }}
          target: test
      - name: Test
        run: DOCKER_BUILDKIT=1 docker compose run --rm bats test
      - name: Push
        uses: docker/build-push-action@v6.18.0
        with:
          build-args: |
            PG_MAJOR=${{ matrix.pg }}
            PGRST_MAJOR=${{ matrix.pgrst }}
          push: true
          tags: technowledgy/pgrst_dev:pg${{ matrix.pg }}-pgrst${{ matrix.pgrst }}

  dockerhub:
    needs: build-test-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v4.0.2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
